name = "hn-distill-pipeline"
main = "worker/src/index.ts"
compatibility_date = "2026-01-21"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "hn-distill-data"

[[d1_databases]]
binding = "DB"
database_name = "hn_distill"
database_id = "fcdf0fb6-2761-492d-a222-1a6218f76fda"
